### ISSUE TITLE
Add lmug-mw-resource

### ISSUE THREAD

**Issue by oubiwann** [lfe-mug/lmug#7]
See: https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/resource.clj

Tasks:
* [x] File system support functions (results unified in maps)
* [x] HTTP response support (body, content type, content length, last modified)
* [x] Core middleware functionality
* [x] Support the option of checking the handler first, and only doing static lookups after the handlers
* [x] Pre-load support
  * [x] Implement it (on by default)
  * [x] When walking the filesystem, track state (current file count, total bytes read, doc-root)
  * [x] Store final state as metadata on key of "resources" map
  * [x] Add functions to gen_server for extracting this metadata from the state
  * [x] Introduce default checks for max files, max file size, max total bytes
  * [x] Add sane default values for these in the options
  * [x] Functionality for manually regenerating in-memory store of static resources
  * [x] #43
  * [x] The ability to turn off pre-loading and do a filesystem read with every request
* [x] Tighten up static-first support, passing off to the handler in the event of a 404

**Comment by yurrriq** [comment]
See [my comment](https://github.com/lfe-mug/lmug/issues/17#issuecomment-207892645) re: `lmug-mw-file`.

**Comment by oubiwann** [comment]
We're doing what Clojure does for this: no file handling by the underlying HTTP server, rather the middleware itself is entirely responsible for reading files and creating responses with bytes from files.

Note that we are supporting the option of "pre-loading": reading resources into memory (with safe max file counts, max file sizes, and max total bytes) during the middleware-wrap (setup) phase, so that as requests come in, the lmug state has already been updated to hold a map of URL paths -> bytes from files, and content can be provided without any filesystem reads.

The first draft of this is done, and awaiting testing ...

**Comment by oubiwann** [comment]
Testing succeeded first try! 

On to all the other bullet items in the feature description ...

**Comment by oubiwann** [comment]
Dunno if this works still ... https://github.com/5HT/fs (for watching fs, re-gen'ing in-mem store).

**Comment by oubiwann** [comment]
I've moved these into their own tickets (in the Backlog milestone):
* [ ] Add default error pages
* [ ] Add support for user-provided error pages
* [ ] Support directory -> "index.html" lookups
* [ ] Support multiple resource directories (last resources added, wins -- in the event over overlap/duplication)
